### ISSUE TITLE
Yaml file config - how to?

### ISSUE THREAD

**Issue by churchofnoise** [mdouchement/captive#3]
Hi,

Very happy to have found your excellent initiative here!

Just tried to run it using a basic yaml file but it seems not to work (I'm adding it to a file that already exists to create Pi-Hole and Unbound containers)
When I look at running containers, this one is not up, but gives a time since restarting...

Is there anything I'm missing:

```
version: "3"

services:
  pihole:
    hostname: firewalla
    container_name: pihole
    image: pihole/pihole:nightly
    networks:
      default:
        ipv4_address: 172.16.0.2
    environment:
      TZ: [EDITED OUT]
      DNS1: '172.16.0.4'
      DNS2: '172.16.0.4'
      WEBPASSWORD: [EDITED OUT]
    volumes:
      - '/data/pi-hole/etc-pihole:/etc/pihole'
      - './etc-dnsmasq:/etc/dnsmasq.d'
      - '/etc/localtime:/etc/localtime:ro'
    restart: unless-stopped
    links:
      - unbound

  unbound:
    image: klutchell/unbound:main
    networks:
      default:
        ipv4_address: 172.16.0.4
    ports:
      - 5335:5335/tcp
      - 5335:5335/udp
    restart: unless-stopped
    volumes:
      - './unbound-conf:/etc/unbound/custom.conf.d'

  captive:
    image: mdouchement/captive:latest
    networks:
      default:
        ipv4_address: 172.16.0.5
    restart: unless-stopped

networks:
  default:
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.0.0/24
```

Thanks in advance for the help!
